### ISSUE TITLE
:(

### ISSUE THREAD

**Issue by nonrice** [aphrim/shogun-engine#2]
<img width="768" alt="Screen Shot 2022-10-24 at 6 31 32 PM" src="https://user-images.githubusercontent.com/17582488/197642280-21a198a6-8938-465b-acfe-496dfcda4891.png">

**Comment by aphrim** [comment]
I think that is due to make using an older version of C++ as Braced Initialization was introduced in C++11 and maybe your compiler is using before C++11?, I will specify C++ version in CMakeFile as well in next commit.
